[project]
name = "myproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "shahzeb", email = "zeb84250@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
myproject = "myproject:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "projectName",
]
